sudo: false
language: rust
cache:
  directories:
  - $HOME/.cache/rocksdb
  - $HOME/.cache/kcov
  - $HOME/.cache/etcd

matrix:
  include:
    - os: linux
      rust: nightly
      compiler: g++
      env: COMPILER=g++-4.8
      addons:
         apt:
            sources: ['ubuntu-toolchain-r-test']
            packages: ['g++-4.8', 'zlib1g-dev', 'libbz2-dev', 'libsnappy-dev', 'libjemalloc-dev', 'curl', 'libdw-dev', 'libelf-dev', 'elfutils', 'binutils-dev']
    - os: osx
      rust: nightly

install:
  - export KCOV_DIR=$HOME/.cache/kcov
  - export ROCKSDB_DIR=$HOME/.cache/rocksdb
  - export ETCD_DIR=$HOME/.cache/etcd
  - make -f travis-build/Makefile prepare_${TRAVIS_OS_NAME}

script:
  - export ETCD_DIR=$HOME/.cache/etcd
  - export PATH=${ETCD_DIR}:${PATH}
  - make -f travis-build/Makefile test_${TRAVIS_OS_NAME}

after_success:
  # TODO add following into build progress after failed cases are resolved.
  - make -f travis-build/Makefile cover_${TRAVIS_OS_NAME}
